### ISSUE TITLE
How to set default user?

### ISSUE THREAD

**Issue by dvzubarev** [KarimAziev/igist#3]
Hi, first of all, thank you very much for this  awesome package!
As far as I understand I have to set `igist-current-user-name` before I can use all gist functions. Also it seems I have  to set it each time after emacs restart. I have only one account and it would be convenient for me to set this one user automatically. 
Did not find  a way to set default user automatically.

**Comment by KarimAziev** [comment]
@dvzubarev  Hi. Just set a value to the variable \`igist-current-user-name\`, e.g.

``` elisp
(setq igist-current-user-name "dvzubarev")
```

Or if you use \`use-package\`:

``` elisp
(use-package igist
  :straight (igist
             :repo "KarimAziev/igist"
             :type git
             :host github)
  :config
  (setq igist-current-user-name "dvzubarev")
  )
```

Note, if you use auth sources, then the following entry should be present:

``` elisp
machine api.github.com login dvzubarev^igist password YOU_GITHUB_TOKEN
```
If you don't use auth sources, or, if you want also persist the GitHub token, you should set value of \`igist-auth-marker'.

``` elisp
(setq igist-auth-marker "YOUR_GITHUB_TOKEN")
```

**Comment by dvzubarev** [comment]
Thank you!
