### ISSUE TITLE
Making `igist-current-user-name` customizable

### ISSUE THREAD

**Issue by danielfleischer** [KarimAziev/igist#4]
Hi, first of all great package. 

Related to #3, of course one can set `igist-current-user-name` manually, but please consider making the variable a customized variable instead of `defvar` which helps people both to **discover** it and to explicitly set it, because it is really not encouraged for end users to explicitly set `defvar` variables as part of their configuration; just a convention issue. 

Since it's probably a common issue (users having a single, main github profile) maybe show that example in the readme. Thanks!

**Comment by KarimAziev** [comment]
Thank you for your feedback and suggestion. Making `igist-current-user-name` a customized variable is indeed a good idea. I will implement this change in the package.

**Comment by KarimAziev** [comment]
@danielfleischer I have made the variable `igist-current-user-name` a customized variable instead of a `defvar` and updated the README. Feel free to reach out if you have any further questions or concerns. Thanks again!
