### ISSUE TITLE
BACKGROUND in docstring may have some issues

### ISSUE THREAD

**Issue by include-yy** [KarimAziev/igist#6]
Hi, this package is very useful to me and I use it for single-file emacs config with gist.

When I read some docstring in igist.el, I noticed that `BACKGROUND` appears in `igist-list-load-gists`, `igist-list-request`, `igist-explore-public-gists` and `igist-list-starred`'s docstring, the first, thrid and fourth said that `If BACKGROUND is nil, don't show user's buffer.`, but I think it should be `If BACKGROUND is non-nil, don't show buffer.` Since in `igist-list-request` the variable `backgroun` is used like this:
```
 (unless background
          (igist-ensure-buffer-visible buffer))))))
```

Also, `BACKGROUND` in `igist-list-starred`'s docstring could be deleted, because there is no `background` arg in arglist.

Regards.

**Comment by KarimAziev** [comment]
@include-yy  Thank you for bringing this to our attention. The documentation indeed was inaccurate. I have updated the docstrings in these functions to align with the actual programmatic usage of `BACKGROUND` . Please feel free to check out the [commit](https://github.com/KarimAziev/igist/commit/98fba8c16a1965c6a319e300d7e3f0b70c160afb) that fixes this issue and let me know if you have any other suggestions or comments.

**Comment by include-yy** [comment]
> I have updated the docstrings in these functions to align with the actual programmatic usage of BACKGROUND .

Thanks! That really makes it clearer, it took me some time to get the idea that some of them were async functions we I saw `callback` argument at the first time. I think now the docstring is more friendly to whom not familiar with async or callback.
